### ISSUE TITLE
Your installed Caffe2 version uses CUDA but I cannot find the CUDA

### ISSUE THREAD

**Issue by wencan** [SHI-Labs/NATTEN#103]
I tried to install NATTEN on a laptop without a graphics card to test its performance on the CPU. However, the installation failed.

Fedora Linux 39 (Workstation Edition)
Linux Kernel: 6.7.4-200.fc39.x86_64
Command: python3.10 -m pip install natten

```
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      Building NATTEN for CPU ONLY.
      Number of workers: 3
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/__init__.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/flops.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/functional.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten1d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten2d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten3d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/nested.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/ops.py -> build/lib.linux-x86_64-cpython-310/natten
      creating build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/tensor.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/testing.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/typing.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      running build_ext
      -- The CXX compiler identification is GNU 13.2.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Python: /usr/bin/python3.10
      CUDA_TOOLKIT_ROOT_DIR not found or specified
      -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)
      CMake Warning at /home/wencan/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
        Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
        or a Caffe2 dependent library, the next warning / error will give you more
        info.
      Call Stack (most recent call first):
        /home/wencan/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:87 (include)
        /home/wencan/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
        CMakeLists.txt:56 (find_package)
      
      
      CMake Error at /home/wencan/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:91 (message):
        Your installed Caffe2 version uses CUDA but I cannot find the CUDA
        libraries.  Please set the proper CUDA prefixes and / or install CUDA.
      Call Stack (most recent call first):
        /home/wencan/.local/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
        CMakeLists.txt:56 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qlfebk2v/natten_b33c063890a7434d87f673f5add0a436/setup.py", line 211, in <module>
          setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-qlfebk2v/natten_b33c063890a7434d87f673f5add0a436/setup.py", line 193, in build_extension
          subprocess.check_call(
        File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-qlfebk2v/natten_b33c063890a7434d87f673f5add0a436/csrc', '-DPYTHON_PATH=/usr/bin/python3.10', '-DOUTPUT_FILE_NAME=natten/libnatten.cpython-310-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
ERROR: Could not build wheels for natten, which is required to install pyproject.toml-based projects

```

**Comment by alihassanijr** [comment]
The issue is like many cases torch's dependency on Caffe2.

Have you tried using wheels instead?

https://shi-labs.com/natten/

**Comment by wencan** [comment]
@alihassanijr 
tks
I successfully installed natten using the following command, and the simple inference test also passed successfully.

```
python3.10 -m pip install natten==0.15.1+torch220cpu -f https://shi-labs.com/natten/wheels
```
