### ISSUE TITLE
Natten package installation error with H100

### ISSUE THREAD

**Issue by justin4ai** [SHI-Labs/NATTEN#135]
Hello, my machine is H100 and I'm trying to install your package with pip. But I keep encountering the following error messages:

```

Collecting natten
  Downloading natten-0.17.1.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 8.2 MB/s 
Collecting packaging
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Requirement already satisfied: torch>=2.0.0 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from natten) (2.3.0+cu118)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.8.86)
Requirement already satisfied: networkx in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.8.89)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.11.3.6)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.8.89)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.4.1.48)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (10.3.0.86)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (4.9.0)
Requirement already satisfied: jinja2 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (3.1.3)
Requirement already satisfied: fsspec in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (2024.2.0)
Requirement already satisfied: triton==2.3.0 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (2.3.0)
Requirement already satisfied: nvidia-nccl-cu11==2.20.5 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (2.20.5)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (10.9.0.58)
Requirement already satisfied: sympy in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (1.12)
Requirement already satisfied: filelock in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (3.13.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.7.5.86)
Requirement already satisfied: nvidia-cudnn-cu11==8.7.0.84 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (8.7.0.84)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from torch>=2.0.0->natten) (11.8.87)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from jinja2->torch>=2.0.0->natten) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages (from sympy->torch>=2.0.0->natten) (1.3.0)
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/miniforge3/envs/unleashing/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v8up2j_e
       cwd: /tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/
  Complete output (93 lines):
  Building NATTEN with CUDA 118
  Building NATTEN for SM: 9.0
  Number of workers: 4
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/natten
  copying src/natten/ops.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/types.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/nested.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/flops.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/na1d.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/na2d.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/context.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/natten2d.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/functional.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/__init__.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/na3d.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/natten3d.py -> build/lib.linux-x86_64-3.8/natten
  copying src/natten/natten1d.py -> build/lib.linux-x86_64-3.8/natten
  creating build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/tensor.py -> build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/checks.py -> build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/log.py -> build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/testing.py -> build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/__init__.py -> build/lib.linux-x86_64-3.8/natten/utils
  copying src/natten/utils/misc.py -> build/lib.linux-x86_64-3.8/natten/utils
  creating build/lib.linux-x86_64-3.8/natten/autotuner
  copying src/natten/autotuner/fna_backward.py -> build/lib.linux-x86_64-3.8/natten/autotuner
  copying src/natten/autotuner/fna_forward.py -> build/lib.linux-x86_64-3.8/natten/autotuner
  copying src/natten/autotuner/__init__.py -> build/lib.linux-x86_64-3.8/natten/autotuner
  copying src/natten/autotuner/misc.py -> build/lib.linux-x86_64-3.8/natten/autotuner
  creating build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_backward_64x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_forward_64x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_forward_64x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_forward_32x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_backward_128x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/fna_backward_128x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  copying src/natten/autotuner/configs/__init__.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 162, in build_extension
      subprocess.check_output(["cmake", "--version"])
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 243, in <module>
      setup(
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 164, in build_extension
      raise RuntimeError("Cannot find CMake executable")
  RuntimeError: Cannot find CMake executable
  ----------------------------------------
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
Installing collected packages: packaging, natten
    Running setup.py install for natten ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/miniforge3/envs/unleashing/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wv1xxqd3/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/miniforge3/envs/unleashing/include/python3.8/natten
         cwd: /tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/
    Complete output (95 lines):
    Building NATTEN with CUDA 118
    Building NATTEN for SM: 9.0
    Number of workers: 4
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/natten
    copying src/natten/ops.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/types.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/nested.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/flops.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/na1d.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/na2d.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/context.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/natten2d.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/functional.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/__init__.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/na3d.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/natten3d.py -> build/lib.linux-x86_64-3.8/natten
    copying src/natten/natten1d.py -> build/lib.linux-x86_64-3.8/natten
    creating build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/tensor.py -> build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/checks.py -> build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/log.py -> build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/testing.py -> build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/__init__.py -> build/lib.linux-x86_64-3.8/natten/utils
    copying src/natten/utils/misc.py -> build/lib.linux-x86_64-3.8/natten/utils
    creating build/lib.linux-x86_64-3.8/natten/autotuner
    copying src/natten/autotuner/fna_backward.py -> build/lib.linux-x86_64-3.8/natten/autotuner
    copying src/natten/autotuner/fna_forward.py -> build/lib.linux-x86_64-3.8/natten/autotuner
    copying src/natten/autotuner/__init__.py -> build/lib.linux-x86_64-3.8/natten/autotuner
    copying src/natten/autotuner/misc.py -> build/lib.linux-x86_64-3.8/natten/autotuner
    creating build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_backward_64x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_forward_64x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_forward_64x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_forward_32x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_backward_128x64.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/fna_backward_128x128.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    copying src/natten/autotuner/configs/__init__.py -> build/lib.linux-x86_64-3.8/natten/autotuner/configs
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 162, in build_extension
        subprocess.check_output(["cmake", "--version"])
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 243, in <module>
        setup(
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/ubuntu/miniforge3/envs/unleashing/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py", line 164, in build_extension
        raise RuntimeError("Cannot find CMake executable")
    RuntimeError: Cannot find CMake executable
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/miniforge3/envs/unleashing/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eu3j4a9z/natten_25f221c9478745c59fbc4edb7d90e944/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wv1xxqd3/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/miniforge3/envs/unleashing/include/python3.8/natten Check the logs for full command output.

```

Any solution about this or related experience? Thanks!

**Comment by alihassanijr** [comment]
Looks like you don't have cmake installed;

If you're looking to pip install, I recommend referring to our webpage:

https://shi-labs.com/natten/

Select your torch + CUDA version, and copy paste the pip command.

Unfortunately we can't have the default wheel be a CUDA build, so the only workaround as of now to support multiple torch builds with different backends is to tag our wheels and use a wheel index manually.

It looks like your installed torch was compiled with CUDA 11.8 by the way; it is highly recommended to switch to builds compiled with 12.1.
You might also want to check your CUDA driver version to make sure it's compatible with CUDA 12.X.

Please let me know if this doesn't solve your issue or if you have more questions.

**Comment by justin4ai** [comment]
Dear Ali,

Thanks for your kind instruction to fix my error, I successfully installed natten package in my environment.

However, I have some more questions about the use of your package - please refer to my issue: https://github.com/SHI-Labs/StyleNAT/issues/15.

Although the error occurs while running StyleNAT, it is definitely about natten package!

Once again, I really appreciate your great work and help with this.

Best Regrads,
Junyeong Ahn

**Comment by justin4ai** [comment]
I close this issue since the problem is solved.
