### ISSUE TITLE
I'm getting a ERROR: Failed building wheel for natten

### ISSUE THREAD

**Issue by aryandaga7** [SHI-Labs/NATTEN#162]
I'm trying to install natten in a virtual environment on my M2 Macbook but I;m getting this error for natten. When I tried installing the same thing on my virtual env I didn't get the issue. I am installing natten because I want to install this API and I followed the usage steps: [https://github.com/mir-aidj/all-in-one](https://github.com/mir-aidj/all-in-one).

**Comment by aryandaga7** [comment]
Here is my cli
`pip install natten
Collecting natten
  Using cached natten-0.17.1.tar.gz (10.8 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: packaging in ./venv/lib/python3.11/site-packages (from natten) (23.2)
Requirement already satisfied: torch>=2.0.0 in ./venv/lib/python3.11/site-packages (from natten) (2.4.0)
Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (4.12.2)
Requirement already satisfied: sympy in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (1.13.2)
Requirement already satisfied: networkx in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (3.3)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (3.1.4)
Requirement already satisfied: fsspec in ./venv/lib/python3.11/site-packages (from torch>=2.0.0->natten) (2024.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->torch>=2.0.0->natten) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.11/site-packages (from sympy->torch>=2.0.0->natten) (1.3.0)
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
      Building NATTEN for CPU ONLY.
      Number of workers: 3
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/natten1d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/natten3d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/natten2d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/na2d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/na3d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/na1d.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/types.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/ops.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/flops.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/functional.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/context.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      copying src/natten/nested.py -> build/lib.macosx-10.9-universal2-cpython-311/natten
      creating build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/misc.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/log.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/checks.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/tensor.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      copying src/natten/utils/testing.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/utils
      creating build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner
      copying src/natten/autotuner/misc.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner
      copying src/natten/autotuner/fna_forward.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner
      copying src/natten/autotuner/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner
      copying src/natten/autotuner/fna_backward.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner
      creating build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_64x128.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_64x64.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_64x64.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_128x64.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_128x128.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_32x128.py -> build/lib.macosx-10.9-universal2-cpython-311/natten/autotuner/configs
      running build_ext
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Python: /Users/aryandaga/AI-DJ/venv/bin/python3.11
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/__init__.py", line 289, in <module>
          _load_global_deps()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/__init__.py", line 245, in _load_global_deps
          raise err
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/__init__.py", line 226, in _load_global_deps
          ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
          self._handle = _dlopen(self._name, mode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: dlopen(/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (no such file), '/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
      CMake Error at CMakeLists.txt:40 (message):
        Python launch failed.
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pg/hgpy459562v0yblp9qpncnk80000gn/T/pip-install-shjf90zg/natten_1663f56264e54c23a40cb56812b45b7c/setup.py", line 243, in <module>
          setup(
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/Users/aryandaga/AI-DJ/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/pg/hgpy459562v0yblp9qpncnk80000gn/T/pip-install-shjf90zg/natten_1663f56264e54c23a40cb56812b45b7c/setup.py", line 219, in build_extension
          subprocess.check_call(
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/pg/hgpy459562v0yblp9qpncnk80000gn/T/pip-install-shjf90zg/natten_1663f56264e54c23a40cb56812b45b7c/csrc', '-DPYTHON_PATH=/Users/aryandaga/AI-DJ/venv/bin/python3.11', '-DOUTPUT_FILE_NAME=natten/libnatten.cpython-311-darwin', '-DNATTEN_CUDA_ARCH_LIST=', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=1', '-DIS_LIBTORCH_BUILT_WITH_CXX11_ABI=0', '-DNATTEN_WITH_AVX=1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (natten)`

**Comment by alihassanijr** [comment]
It looks like the detected torch installation is targeting the wrong architecutre (x86-64 instad of arm), but this could also be a compiler issue.
Can you try starting an interactive python session and running this, and see whether it succeeds?

Just run:
```bash
/Users/aryandaga/AI-DJ/venv/bin/python3.11
```

and then
```python
import torch
torch.__version__
```

**Comment by aryandaga7** [comment]
Hi. Here is the torch version.
>>> import torch
>>> torch.__version__
'2.4.0'

**Comment by aryandaga7** [comment]
Ok I fixed the error. Here is what I figured. I was using the arm64 architecture for pytorch but to install natten I needed the x86 architecture. So I ran the terminal again but this time checked using rosetta in mac. Then reinstalled pytorch which was this time in x86 architecture. Then I simply installed natten using pip.
