### ISSUE TITLE
Mac: pip install: fatal error: 'cassert' file not found

### ISSUE THREAD

**Issue by drscotthawley** [SHI-Labs/NATTEN#190]
This affects `pip3 install natten` on Mac OS 15.1 and 15.2 with Python 3.10.  
Hi folks!  I searched the Issues for this error but am not seeing it.  

Searching the internet, this seems like a problem that affects several other projects when building for Mac, so it's not unique to NATTEN.  

I'll try to find the appropriate fix or workaround myself and post it in a reply shortly.  And then probably close this issue.   

So far, I've tried 
- Updating the OS
- Updating Xcode Developer tools
- rebooting

....No effect. Will keep trying.

Log follows...

```
$ pip3 install natten
Collecting natten
  Using cached natten-0.17.3.tar.gz (10.8 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: packaging in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from natten) (24.2)
Requirement already satisfied: torch>=2.0.0 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from natten) (2.5.1)
Requirement already satisfied: filelock in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (4.12.2)
Requirement already satisfied: networkx in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (3.4.2)
Requirement already satisfied: jinja2 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (3.1.5)
Requirement already satisfied: fsspec in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (2024.12.0)
Requirement already satisfied: sympy==1.13.1 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from torch>=2.0.0->natten) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from sympy==1.13.1->torch>=2.0.0->natten) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/myusername/envs/myenv/lib/python3.10/site-packages (from jinja2->torch>=2.0.0->natten) (3.0.2)
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [133 lines of output]
      Building NATTEN for CPU ONLY.
      Number of workers: 2
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/natten1d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/natten3d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/natten2d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/na2d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/na3d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/na1d.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/__init__.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/types.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/ops.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/flops.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/functional.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/context.py -> build/lib.macosx-15-arm64-cpython-310/natten
      copying src/natten/nested.py -> build/lib.macosx-15-arm64-cpython-310/natten
      creating build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/misc.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/log.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/checks.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/__init__.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/tensor.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      copying src/natten/utils/testing.py -> build/lib.macosx-15-arm64-cpython-310/natten/utils
      creating build/lib.macosx-15-arm64-cpython-310/natten/autotuner
      copying src/natten/autotuner/misc.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner
      copying src/natten/autotuner/fna_forward.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner
      copying src/natten/autotuner/__init__.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner
      copying src/natten/autotuner/fna_backward.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner
      creating build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_64x128.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_64x64.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_64x64.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_128x64.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/__init__.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_backward_128x128.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      copying src/natten/autotuner/configs/fna_forward_32x128.py -> build/lib.macosx-15-arm64-cpython-310/natten/autotuner/configs
      running build_ext
      -- The CXX compiler identification is AppleClang 16.0.0.16000026
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Python: /Users/myusername/envs/myenv/bin/python3.10
      Torch dir: /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch
      Torch include dir: /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include
      Building NATTEN on MacOS.
      Building with -D_GLIBCXX_USE_CXX11_ABI=0
      -- Configuring done (7.2s)
      -- Generating done (0.0s)
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          NATTEN_CUDA_ARCH_LIST
      
      
      -- Build files have been written to: /private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/build/lib.macosx-15-arm64-cpython-310
      [ 15%] Building CXX object CMakeFiles/natten.dir/autogen/src/cpu/naive/source_1.cpp.o
      [ 15%] Building CXX object CMakeFiles/natten.dir/autogen/src/cpu/naive/source_0.cpp.o
      In file included from /private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/csrc/autogen/src/cpu/naive/source_0.cpp:2:
      In file included from In file included from /private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/csrc/autogen/src/cpu/naive/source_1.cpp:2:
      In file included from /private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/csrc/./include/natten/cpu/naive/inverse_neighborhood_1d.hpp:32:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/Context.h:3:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/BlasBackend.h:3/private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/csrc/./include/natten/cpu/naive/neighborhood_neighborhood_1d.hpp:32:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/Context.h:3:
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/ATen/BlasBackend.h:3:
      :
      In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:In file included from /Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:5:
      5/Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/c10/macros/Macros.h:
      :/Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/c10/macros/Macros.h3::310::10 :fatal error:  'cassert' file not foundfatal error:
      'cassert' file not found
          3 | #incl    u3d | e# i<nccludeassert>
            |           ^~~~~~~~~<
      cassert>
            |          ^~~~~~~~~
      1 error generated.
      1 error generated.
      make[2]: *** [CMakeFiles/natten.dir/autogen/src/cpu/naive/source_1.cpp.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
      make[2]: *** [CMakeFiles/natten.dir/autogen/src/cpu/naive/source_0.cpp.o] Error 1
      make[1]: *** [CMakeFiles/natten.dir/all] Error 2
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/setup.py", line 243, in <module>
          setup(
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/Users/myusername/envs/myenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/5s/dkk8t0jn5fv6df9f68j9xddr0000gn/T/pip-install-r8y_cmt1/natten_bcd49c7f435741df8c33658624f87258/setup.py", line 230, in build_extension
          subprocess.check_call(["cmake", *cmake_build_args])
        File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', 'build/lib.macosx-15-arm64-cpython-310', '-j', '2']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (natten)
```

Will update when/if I fix it. Happy to receive tips from others. ;-)

**Comment by drscotthawley** [comment]
Besides the OS & XCode tools upgrade, the following...

```
brew update
brew upgrade 
```
upgrades many things, including new versions `llvm` and `glib`
We'll see if that fixes it...

**Comment by drscotthawley** [comment]
More info: 

```
$ gcc --version
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin24.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ which gcc
/usr/bin/gcc
```

Looking at https://github.com/ollama/ollama/issues/7392, it's possibile that there's a mismatch between the Homebrew `gcc` and the default Apple one/`clang`.  Not sure yet.

**Comment by alihassanijr** [comment]
@drscotthawley just out of curiosity, did you upgrade your macos recently?

The error seems to originate from PyTorch headers and not NATTEN's:

```
      :/Users/myusername/envs/myenv/lib/python3.10/site-packages/torch/include/c10/macros/Macros.h3::310::10 :fatal error:  'cassert' file not foundfatal error:
      'cassert' file not found
          3 | #incl    u3d | e# i<nccludeassert>
            |           ^~~~~~~~~<
```

Unrelated to this, many of my typical build scripts tend to fail on the most recent macos. 

So I think it is possible it's something yet to be fixed in the next torch release.

But aside from this, I think if you do have a CUDA environment, you should definitely use that, because everywhere else the only option that NATTEN offers right now is just CPU kernels, which are not optimized for performance even on CPU.

**Comment by drscotthawley** [comment]
@alihassanijr Correct, my MacOS was recently updated. In fact I updated *again* (from 15.1 to 15.2) after I first saw this error.

**Comment by drscotthawley** [comment]
> so you might need to upgrade something like xcode or build tools.

?  As I said in the OP...

>So far, I've tried
> 
> - Updating the OS
> - Updating Xcode Developer tools

and then again later...

> Besides the OS & XCode tools upgrade,....`brew upgrade`

Also noted that this is not NATTEN-specific.

Haven't found a solution yet because I've taken a few days off and am just running on Linux instead.

Feel free to close, though I suspect many other users will have this issue too, and once it gets figured out, this thread can serve as a useful resource.
