### ISSUE TITLE
Trouble Installing 

### ISSUE THREAD

**Issue by ciaranby** [SHI-Labs/NATTEN#3]
Hi, was wondering if someone can help with installing this. I am getting the below issues when trying to install.

```
pip3 install natten -f https://shi-labs.com/natten/wheels/cu101/torch1.12/index.html
Looking in links: https://shi-labs.com/natten/wheels/cu101/torch1.12/index.html
Collecting natten
  Using cached natten-0.14.2-4.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/61/5c/41704bc27a54c0a3cf5bc2a7a98b488382524a1b68cf395e25d2591dea55/natten-0.14.2-4.tar.gz (from https://pypi.org/simple/natten/) (requires-python:>=3.7): Requested natten from https://files.pythonhosted.org/packages/61/5c/41704bc27a54c0a3cf5bc2a7a98b488382524a1b68cf395e25d2591dea55/natten-0.14.2-4.tar.gz has inconsistent version: expected '0.14.2.post4', but metadata has '0.14.2+torch112cu102'
ERROR: Could not find a version that satisfies the requirement natten (from versions: 0.14.1, 0.14.2.post4)
ERROR: No matching distribution found for natten
```

I have also tried using pip's legacy resolver leading to the below issues. I have also tried building from source which leads to the same issue as below. 

```
pip3 install natten --use-deprecated=legacy-resolver -f https://shi-labs.com/natten/wheels/cu101/torch1.12/index.html
Looking in links: https://shi-labs.com/natten/wheels/cu101/torch1.12/index.html
Collecting natten
  Using cached natten-0.14.2-4.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/natten
      copying natten/__init__.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/flops.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/functional.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/natten1d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/natten2d.py -> build/lib.linux-x86_64-cpython-310/natten
      running build_ext
      building 'natten._C' extension
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten/src
      Emitting ninja build file /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: '/tmp/pip-install-3gvwtk3x/natten/natten/src/natten.cpp', needed by '/tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten/src/natten.o', missing and no known rule to make it
      Traceback (most recent call last):
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3gvwtk3x/natten/setup.py", line 105, in <module>
          setup(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
Installing collected packages: pyparsing, packaging, natten
  Running setup.py install for natten ... error
  error: subprocess-exited-with-error

  × Running setup.py install for natten did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      running install
      /home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/natten
      copying natten/__init__.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/flops.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/functional.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/natten1d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying natten/natten2d.py -> build/lib.linux-x86_64-cpython-310/natten
      running build_ext
      building 'natten._C' extension
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten
      creating /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten/src
      Emitting ninja build file /tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: '/tmp/pip-install-3gvwtk3x/natten/natten/src/natten.cpp', needed by '/tmp/pip-install-3gvwtk3x/natten/build/temp.linux-x86_64-cpython-310/tmp/pip-install-3gvwtk3x/natten/natten/src/natten.o', missing and no known rule to make it
      Traceback (most recent call last):
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3gvwtk3x/natten/setup.py", line 105, in <module>
          setup(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 692, in run
          self.run_command('build')
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/ciaran.byrne/anaconda3/envs/natten/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> natten

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by alihassanijr** [comment]
Hello, and thanks for sharing this.

The issue I'm seeing is probably that the wheel is recognized, but pip is ignoring the wheel, so it's trying to manually compile (which is buggy in this release and will be resolved in the next).
Could you share your Python version?

**Comment by alihassanijr** [comment]
I'm closing this due to inactivity. 
I'll also add that the new release (0.14.4) would avoid this issue: if no wheel URL is specified, or it is incorrect, pip will just grab the source dist and compile on your system. It will just be slower, since it's effectively compiling the entire package on your system, and to my knowledge ignores ninja.

Please feel free to reopen it if you should run into any more issues or still have questions.
