### ISSUE TITLE
Support for Cuda 12 and PyTorch 2.1.0

### ISSUE THREAD

**Issue by littlespray** [SHI-Labs/NATTEN#57]
Thank you for your nice work!

Does NATTEN supports the installation for cuda 12.1 and PyTorch 2.1.0?

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

Yes, it should work as long as you build from source, which is recommended since we haven't been able to push out new releases for a few months now (I just haven't had the bandwidth to figure out building fat binaries with the GEMM kernels targeting different architectures.)

May I ask what GPU architecture you're using?

**Comment by littlespray** [comment]
Hello, thank you for your reply. My GPU arch is 70 (NVIDIA Tesla V100). When I run the "make" command in the NATTEN 
directory, it raises the following errors:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "NATTEN/setup.py", line 213, in <module>
        setup(
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup        dist.run_commands()      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.8/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/lib/python3.8/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "NATTEN/setup.py", line 210, in build_extension
        subprocess.check_call(['make', f"-j{n_workers}"], cwd=self.build_lib)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j5']' returned non-zero exit status 2.
    Current arch: 70
ERROR: Command errored out with exit status 1: /usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'NATTEN/setup.py'"'"'; __file__='"'"'NATTEN/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 23.3 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
```

May you provide some suggestions?

**Comment by alihassanijr** [comment]
Then I'd highly recommend building from source, which you're already doing.

As for the error, can you please share `install.out`? make should dump that in your working directory, and it will contain the full log suggesting exactly what went wrong. What you just shared doesn't really reflect anything other than the failure, which is standard given how verbose the output is.

**Comment by littlespray** [comment]
Thank you for your advice. The install.out shows that " NATTEN/csrc/./include/natten/cuda/gemm/threadblock/threadblock_swizzle.cuh:47:10: fatal error: cutlass/gemm/threadblock/index_remat.h: No such file or directory" Are there any packages that needs to be installed?

**Comment by alihassanijr** [comment]
Yes; it looks like the cutlass submodule wasn't cloned (that's strange because make is supposed to do that.)

Can you run this and try again?

```
git submodule update --init --recursive
```

If it doesn't work, feel free to just share the entire file and I'll take a look.

**Comment by alihassanijr** [comment]
Closing due to inactivity. Feel free to reopen if you have more questions.
