### ISSUE TITLE
Linux installation error: Python launch failed.

### ISSUE THREAD

**Issue by Eddie-yz** [SHI-Labs/NATTEN#88]
Hi, thanks for the library! I'm trying to install natten on linux by `pip3 install natten`, but it failed and gave the error below:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting natten
  Using cached natten-0.15.0.tar.gz (1.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: packaging in /home/algo/.local/lib/python3.10/site-packages (from natten) (23.2)
Requirement already satisfied: cmake==3.20.3 in /home/algo/.local/lib/python3.10/site-packages (from natten) (3.20.3)
Requirement already satisfied: torch>=2.0.0 in /home/algo/.local/lib/python3.10/site-packages (from natten) (2.0.1+cu118)
Requirement already satisfied: filelock in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (3.13.0)
Requirement already satisfied: networkx in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (2.2)
Requirement already satisfied: triton==2.0.0 in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (2.0.0)
Requirement already satisfied: sympy in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (1.12)
Requirement already satisfied: typing-extensions in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (4.4.0)
Requirement already satisfied: jinja2 in /home/algo/.local/lib/python3.10/site-packages (from torch>=2.0.0->natten) (3.1.2)
Requirement already satisfied: lit in /home/algo/.local/lib/python3.10/site-packages (from triton==2.0.0->torch>=2.0.0->natten) (15.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in /home/algo/.local/lib/python3.10/site-packages (from jinja2->torch>=2.0.0->natten) (2.1.2)
Requirement already satisfied: decorator>=4.3.0 in /home/algo/.local/lib/python3.10/site-packages (from networkx->torch>=2.0.0->natten) (5.1.1)
Requirement already satisfied: mpmath>=0.19 in /home/algo/.local/lib/python3.10/site-packages (from sympy->torch>=2.0.0->natten) (1.3.0)
Installing collected packages: natten
  DEPRECATION: natten is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for natten: started
  Running setup.py install for natten: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for natten did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      Building NATTEN with CUDA 118
      Building NATTEN for SM: 8.9
      Number of workers: 1
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/__init__.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten3d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten1d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/functional.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/natten2d.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/flops.py -> build/lib.linux-x86_64-cpython-310/natten
      copying src/natten/nested.py -> build/lib.linux-x86_64-cpython-310/natten
      creating build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/testing.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/tensor.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      copying src/natten/utils/typing.py -> build/lib.linux-x86_64-cpython-310/natten/utils
      running build_ext
      Current arch list: [89] (max: 89)
      -- The CXX compiler identification is GNU 8.3.0
      -- The CUDA compiler identification is NVIDIA 12.2.140
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Looking for C++ include pthread.h
      -- Looking for C++ include pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda-12.2 (found suitable version "12.2", minimum required is "11.0")
      Building NATTEN with CUDA.
      -- Found Python: /usr/local/bin/python3.10 (found suitable version "3.10.12", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ImportError: No module named torch
      CMake Error at CMakeLists.txt:34 (message):
        Python launch failed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-p_zo10cc/natten_50777cd7748c4b0686bc702f7fffe486/build/lib.linux-x86_64-cpython-310/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-p_zo10cc/natten_50777cd7748c4b0686bc702f7fffe486/build/lib.linux-x86_64-cpython-310/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p_zo10cc/natten_50777cd7748c4b0686bc702f7fffe486/setup.py", line 210, in <module>
          setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-p_zo10cc/natten_50777cd7748c4b0686bc702f7fffe486/setup.py", line 192, in build_extension
          subprocess.check_call(
        File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-p_zo10cc/natten_50777cd7748c4b0686bc702f7fffe486/csrc', '-DOUTPUT_FILE_NAME=natten/libnatten.cpython-310-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=89-real', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1', '-DNATTEN_WITH_CUDA=1', '-DNATTEN_WITH_CUTLASS=1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> natten

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip3.10 install --upgrade pip
```

However, I do have pytorch installed and it works fine. When I run `python3 -c "import torch; print(torch.__version__); print(torch.__config__.show())"`, it returns:
```
2.0.1+cu118
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
```

Does anyone encounter a similar issue or know what's happening here? Thanks!

**Comment by alihassanijr** [comment]
It looks like CMake is picking a different python installation on your system. 
You shouldn't have to build from source unless you're interested in a very recent feature.

You can just refer to [our website](https://shi-labs.com/natten/) and pick your torch / cuda version, and it'll give you a pip install command with a link to our prebuilt wheels. That should be a faster install as well.

However, if you still want to build from source, kindly run these commands and share their outputs:

```
which python3

echo $PATH
```

**Comment by Eddie-yz** [comment]
> It looks like CMake is picking a different python installation on your system. You shouldn't have to build from source unless you're interested in a very recent feature.
> 
> You can just refer to [our website](https://shi-labs.com/natten/) and pick your torch / cuda version, and it'll give you a pip install command with a link to our prebuilt wheels. That should be a faster install as well.
> 
> However, if you still want to build from source, kindly run these commands and share their outputs:
> 
> ```
> which python3
> 
> echo $PATH
> ```

Hi Ali, thanks for your immediate reply! I installed a prebuilt version and it works well now. Let's close this issue.

**Comment by Eddie-yz** [comment]
> It looks like CMake is picking a different python installation on your system. You shouldn't have to build from source unless you're interested in a very recent feature.
> 
> You can just refer to [our website](https://shi-labs.com/natten/) and pick your torch / cuda version, and it'll give you a pip install command with a link to our prebuilt wheels. That should be a faster install as well.
> 
> However, if you still want to build from source, kindly run these commands and share their outputs:
> 
> ```
> which python3
> 
> echo $PATH
> ```
Hi Ali, thanks for your immediate reply! I installed a prebuilt version and it works well now. Let's close this issue.
