### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._C'

### ISSUE THREAD

**Issue by drscotthawley** [SHI-Labs/NATTEN#99]
Hi, I'm on Linux and I have CUDA 12.2 and Pytorch 2.2.0, which I don't see on [your list of wheels](https://shi-labs.com/natten/wheels/) -- yet. 

So when I try to install with just pip, I get the following...

```bash
$ pip3 install natten
Defaulting to user installation because normal site-packages is not writeable
Collecting natten
  Downloading natten-0.15.1.tar.gz (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mkt6ku4g/natten_83a55432db4c4bfea15a2dadde1ee0f5/setup.py", line 37, in <module>
          from torch.utils.cpp_extension import CUDA_HOME, LIB_EXT
        File "/home/shawley/.local/lib/python3.9/site-packages/torch/utils/__init__.py", line 4, in <module>
          from .throughput_benchmark import ThroughputBenchmark
        File "/home/shawley/.local/lib/python3.9/site-packages/torch/utils/throughput_benchmark.py", line 2, in <module>
          import torch._C
      ModuleNotFoundError: No module named 'torch._C'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Can you offer any suggestions?

I find that I'm manually able to import `torch._C` in my current environment, it's just that the pip version doesn't seem to find it:
```bash
$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch._C
>>> quit()
```
Thanks!

**Comment by alihassanijr** [comment]
Thank you for your interest.
Yes, we still haven't been able to push out a new release since torch 2.2, but the error you shared doesn't appear to be specific to torch 2.2.

It looks like `pip3` is linked to a different python installation / environment on your system, and that environment has an incomplete version of PyTorch installed. The trace is just failing during torch initialization.

From the trace:

Torch is installed at:

```
/home/shawley/.local/lib/python3.9/site-packages/torch
```

But according to the interpreter, you're intended environment is running Python 3.10, not 3.9.

Could you please check these paths?

```
which pip
which pip3

which python
which python3

python -c "import torch; print(torch.__file__)"
python3 -c "import torch; print(torch.__file__)"
```

**Comment by drscotthawley** [comment]
Thank you so much!  Somehow I missed that the versions of python were messed up!

I created fresh venv environments using Python 3.10, but I got a similar error to what you're about to see below.  Still, just to be sure, I went ahead and deleted that 3.10 venv and created a new using Python 3.9, hoping that that might help.. nope. 

Anyway, I'll now stick with Python 3.9 for the rest of this exchange....

Here are the results of the commands you suggested: 
```bash
/home/shawley/envs/new_venv/bin/pip
/home/shawley/envs/new_venv/bin/pip3
/home/shawley/envs/new_venv/bin/python
/home/shawley/envs/new_venv/bin/python3
/home/shawley/envs/new_venv/lib/python3.9/site-packages/torch/__init__.py
/home/shawley/envs/new_venv/lib/python3.9/site-packages/torch/__init__.py
```

Then I ran 
```bash
$ pip3 install torch torchvision torchaudio
```

and then....

```bash
$ pip3 install natten
Collecting natten
  Using cached natten-0.15.1.tar.gz (1.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ko59iw7g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ko59iw7g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ko59iw7g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ko59iw7g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Hmm. Again, I can import torch in the REPL with no problems. Hmm.  I am usually able to build and install packages without difficulty. `natten` is...to my knowledge,... the first package that's exhibited this behavior. Is there something unusual going on under the hood in the setup script? 

Well, I also tried 
```bash
pip3 install wheel
```

and then installing `natten` yielded a new, different error about `cmake` not being installed.  So I installed `cmake`, and then.....


```bash
$ pip3 install natten
Collecting natten
  Using cached natten-0.15.1.tar.gz (1.9 MB)
  Preparing metadata (setup.py) ... done
Collecting packaging (from natten)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting cmake==3.20.3 (from natten)
  Using cached cmake-3.20.3-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (19.4 MB)
Requirement already satisfied: torch>=2.0.0 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from natten) (2.2.0)
Requirement already satisfied: filelock in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (4.9.0)
Requirement already satisfied: sympy in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (1.12)
Requirement already satisfied: networkx in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (3.2.1)
Requirement already satisfied: jinja2 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (3.1.3)
Requirement already satisfied: fsspec in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from torch>=2.0.0->natten) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0.0->natten) (12.3.101)
Requirement already satisfied: MarkupSafe>=2.0 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from jinja2->torch>=2.0.0->natten) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /home/shawley/envs/new_venv/lib/python3.9/site-packages (from sympy->torch>=2.0.0->natten) (1.3.0)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Building wheels for collected packages: natten
  Building wheel for natten (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      Building NATTEN with CUDA 121
      Building NATTEN for SM: 8.6
      Number of workers: 28
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/natten
      copying src/natten/natten1d.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/nested.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/natten2d.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/functional.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/ops.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/flops.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/__init__.py -> build/lib.linux-x86_64-3.9/natten
      copying src/natten/natten3d.py -> build/lib.linux-x86_64-3.9/natten
      creating build/lib.linux-x86_64-3.9/natten/utils
      copying src/natten/utils/typing.py -> build/lib.linux-x86_64-3.9/natten/utils
      copying src/natten/utils/tensor.py -> build/lib.linux-x86_64-3.9/natten/utils
      copying src/natten/utils/testing.py -> build/lib.linux-x86_64-3.9/natten/utils
      copying src/natten/utils/__init__.py -> build/lib.linux-x86_64-3.9/natten/utils
      running build_ext
      Current arch list: [86] (max: 86)
      -- The CXX compiler identification is GNU 11.4.0
      -- The CUDA compiler identification is unknown
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:5 (project):
        No CMAKE_CUDA_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
        path to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-ugvt0utc/natten_1e7ab5b632f34d3291c1903f91d66910/build/lib.linux-x86_64-3.9/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-ugvt0utc/natten_1e7ab5b632f34d3291c1903f91d66910/build/lib.linux-x86_64-3.9/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ugvt0utc/natten_1e7ab5b632f34d3291c1903f91d66910/setup.py", line 211, in <module>
          setup(
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shawley/envs/new_venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-ugvt0utc/natten_1e7ab5b632f34d3291c1903f91d66910/setup.py", line 193, in build_extension
          subprocess.check_call(
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-ugvt0utc/natten_1e7ab5b632f34d3291c1903f91d66910/csrc', '-DPYTHON_PATH=/home/shawley/envs/new_venv/bin/python3.9', '-DOUTPUT_FILE_NAME=natten/libnatten.cpython-39-x86_64-linux-gnu', '-DNATTEN_CUDA_ARCH_LIST=86-real', '-DNATTEN_IS_WINDOWS=0', '-DNATTEN_IS_MAC=0', '-DNATTEN_WITH_AVX=1', '-DNATTEN_WITH_CUDA=1', '-DNATTEN_WITH_CUTLASS=1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for natten
  Running setup.py clean for natten
Failed to build natten
ERROR: Could not build wheels for natten, which is required to install pyproject.toml-based projects
```

Despite my setting
```
export CUDA_HOME=/usr/local/cuda
export CUDACXX=/usr/local/cuda

``` 
and retrying, it still couldn't find my CUDA installation.

So... I think I'll just wait until you guys get around to building for the versions I have. 
Thanks for your help.   Closing. 

PS- , one thing we've learned so far is that it's essential to have both `wheel` and `cmake` installed before attempting to run `pip3 install natten`.

**Comment by alihassanijr** [comment]
You're welcome.
I'll build wheels for the new release tonight and push them out. Thanks for bringing it to our attention.

In the meantime, could you try setting CUDACXX to the cuda compiler path?
You can find that by doing `which nvcc`.

**Comment by drscotthawley** [comment]
Yes I would/will gladly do so, except I found that `nvcc` wasn't actually on the machine. 

When I went to `sudo apt install nvidia-cuda-toolkit`, it said that my `nvidia-driver-535` didn't agree with the version `495` expected by the toolkit, and it strongly suggested I should reboot...

...and now the (remote) machine won't come back up after the reboot.  So... maybe later this week after receiving on-site support help, I can try again. 👍

**Comment by alihassanijr** [comment]
I'm really sorry for the inconvenience. Yeah, installing/upgrading cuda toolkit can sometimes be a nightmare.
If you didn't have nvcc, you probably could have installed the cuda toolkit through anaconda as well, if you happen to have that.

But anyway, just finished building wheels for torch 2.2.

https://shi-labs.com/natten/

**Comment by drscotthawley** [comment]
Thanks for your help! I got the machine back up, and although I'm still running CUDA 12.3, I'm going to see if the wheel for 12.1 works: 

```bash
pip install natten -f https://shi-labs.com/natten/wheels/cu121/torch2.2.0/natten-0.15.1%2Btorch220cu121-cp310-cp310-linux_x86_64.whl
```
if that fails, I'll try the full build.

**Comment by alihassanijr** [comment]
It should work; If the version of torch you have installed is tagged with `cu121`, it means the binaries were compiled with 12.1, so if torch's CUDA backend works for you, the NATTEN wheel should work just fine.
